### ISSUE TITLE
Gamescope crashes shortly after launching (NVIDIA)

### ISSUE THREAD

**Issue by Weather-OS** [ValveSoftware/gamescope#1167]
**GPU**: NVIDIA GeForce RTX 3060
**WM**: KWin6
**Distro**: Arch

**Gamescope version**: [14a1db3](https://github.com/ValveSoftware/gamescope/commit/14a1db3a57612e5cfbba6d4c19688eafdc6c4043)

**Observed behavior**:
Gamescope is unusable. It launches my game and works fine for like 10 seconds and then promptly freezes followed by `vblankmanager: write failed: Resource temporarily unavailable` errors.
I can only quit gamescope by `kill`ing it with the `-09` flag.
This is the case for every application. I tested it with vkcube as well. same results.

**Expected behavior**:
Gamescope shouldn't freeze and crash.

**Comment by brain-anti-freeze** [comment]
I think that was a driver bug (I had it too but the latest version doesn't seem to be affected)

**Comment by Weather-OS** [comment]
The latest drivers are still affected by this from my testing (550 stable drivers)

**Comment by bno1** [comment]
Similar issue. Arch Linux, Nvidia driver 550.54.14, KDE 6, gamescope 3.14.2. 

`mangohud gamescope vkcube` works fine.
<details>
<summary>log</summary>

```
$ mangohud gamescope vkcube
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
vulkan: selecting physical device 'Intel(R) Graphics (RPL-P)': queue family 0 (general queue family 0)
vulkan: physical device supports DRM format modifiers
wlserver: [backend/headless/backend.c:67] Creating headless backend
vulkan: supported DRM formats for sampling usage:
vulkan:   AR24 (0x34325241)
vulkan:   XR24 (0x34325258)
vulkan:   AB24 (0x34324241)
vulkan:   XB24 (0x34324258)
vulkan:   RG16 (0x36314752)
vulkan:   NV12 (0x3231564E)
vulkan:   AB4H (0x48344241)
vulkan:   XB4H (0x48344258)
vulkan:   AB48 (0x38344241)
vulkan:   XB48 (0x38344258)
vulkan:   AB30 (0x30334241)
vulkan:   XB30 (0x30334258)
vulkan:   AR30 (0x30335241)
vulkan:   XR30 (0x30335258)
vulkan: Creating Gamescope nested swapchain with format 58 and colorspace 0
wlserver: Running compositor on wayland display 'gamescope-0'
wlserver: [backend/headless/backend.c:17] Starting headless backend
wlserver: [xwayland/server.c:108] Starting Xwayland on :1
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Could not resolve keysym XF86CameraAccessEnable
> Warning:          Could not resolve keysym XF86CameraAccessDisable
> Warning:          Could not resolve keysym XF86CameraAccessToggle
> Warning:          Could not resolve keysym XF86NextElement
> Warning:          Could not resolve keysym XF86PreviousElement
> Warning:          Could not resolve keysym XF86AutopilotEngageToggle
> Warning:          Could not resolve keysym XF86MarkWaypoint
> Warning:          Could not resolve keysym XF86Sos
> Warning:          Could not resolve keysym XF86NavChart
> Warning:          Could not resolve keysym XF86FishingChart
> Warning:          Could not resolve keysym XF86SingleRangeRadar
> Warning:          Could not resolve keysym XF86DualRangeRadar
> Warning:          Could not resolve keysym XF86RadarOverlay
> Warning:          Could not resolve keysym XF86TraditionalSonar
> Warning:          Could not resolve keysym XF86ClearvuSonar
> Warning:          Could not resolve keysym XF86SidevuSonar
> Warning:          Could not resolve keysym XF86NavInfo
Errors from xkbcomp are not fatal to the X server
wlserver: [types/wlr_compositor.c:692] New wlr_surface 0x5e93f7d05bd0 (res 0x5e93f7cdfc40)
wlserver: [xwayland/server.c:273] Xserver is ready
pipewire: stream state changed: connecting
pipewire: stream state changed: paused
pipewire: stream available on node ID: 118
vblank: Using timerfd.
vulkan: Creating Gamescope nested swapchain with format 58 and colorspace 0
pipewire: renegotiating stream params (size: 1920x1080)
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
[2024-03-03 00:49:19.382] [MANGOHUD] [error] [overlay_params.cpp:1003] Failed to read presets file: '/home/alex/.config/MangoHud/presets.conf'
Selected GPU 1: NVIDIA GeForce RTX 4070 Laptop GPU, type: DiscreteGpu
[Gamescope WSI] Creating Gamescope surface: xid: 0x400000
[Gamescope WSI] Atom of T was wrong type. Expected XCB_ATOM_CARDINAL.
wlserver: [types/wlr_compositor.c:692] New wlr_surface 0x5e93f7cb3ac0 (res 0x5e93f7ce1880)
wlserver: [types/wlr_compositor.c:692] New wlr_surface 0x5e93f7cb3f80 (res 0x5e93f7ce7c70)
[Gamescope WSI] Made gamescope surface for xid: 0x400000
[Gamescope WSI] Surface state:
  steam app id:                  0
  window xid:                    0x400000
  wayland surface res id:        5
  layer client flags:            0x0
  server hdr output enabled:     false
  hdr formats exposed to client: false
xwm: got the same buffer committed twice, ignoring.
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
> Warning:          Could not resolve keysym XF86CameraAccessEnable
> Warning:          Could not resolve keysym XF86CameraAccessDisable
> Warning:          Could not resolve keysym XF86CameraAccessToggle
> Warning:          Could not resolve keysym XF86NextElement
> Warning:          Could not resolve keysym XF86PreviousElement
> Warning:          Could not resolve keysym XF86AutopilotEngageToggle
> Warning:          Could not resolve keysym XF86MarkWaypoint
> Warning:          Could not resolve keysym XF86Sos
> Warning:          Could not resolve keysym XF86NavChart
> Warning:          Could not resolve keysym XF86FishingChart
> Warning:          Could not resolve keysym XF86SingleRangeRadar
> Warning:          Could not resolve keysym XF86DualRangeRadar
> Warning:          Could not resolve keysym XF86RadarOverlay
> Warning:          Could not resolve keysym XF86TraditionalSonar
> Warning:          Could not resolve keysym XF86ClearvuSonar
> Warning:          Could not resolve keysym XF86SidevuSonar
> Warning:          Could not resolve keysym XF86NavInfo
Errors from xkbcomp are not fatal to the X server
[Gamescope WSI] Creating swapchain for xid: 0x400000 - minImageCount: 3 - format: VK_FORMAT_B8G8R8A8_UNORM - colorspace: VK_COLOR_SPACE_SRGB_NONLINEAR_KHR - flip: true
[Gamescope WSI] Created swapchain for xid: 0x400000 - imageCount: 3
[2024-03-03 00:49:19.536] [MANGOHUD] [error] [nvctrl.cpp:56] XNVCtrl didn't find the correct display
[Gamescope WSI] Swapchain recieved new refresh cycle: 4.17ms
gamescope: Received Terminated signal, forwarding to child!
gamescope: Received Terminated signal, attempting shutdown!
(EE) failed to read Wayland events: Broken pipe
waitable: timerfd_settime failed!: Bad file descriptor

```

</details>

`prime-run manhohud gamescope vkcube` runs for a few seconds then freezes. Red and blue channels are swapped.

<details>
<summary>log</summary>

```
$ prime-run mangohud gamescope vkcube
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
vulkan: physical device 10de:2860 compute queue doesn't support presenting on our surface, using graphics queue
vulkan: selecting physical device 'NVIDIA GeForce RTX 4070 Laptop GPU': queue family 0 (general queue family 0)
vulkan: physical device supports DRM format modifiers
wlserver: [backend/headless/backend.c:67] Creating headless backend
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x38344241 (VkResult: 0)
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x38344258 (VkResult: 0)
vulkan: supported DRM formats for sampling usage:
vulkan:   AR24 (0x34325241)
vulkan:   XR24 (0x34325258)
vulkan:   AB24 (0x34324241)
vulkan:   XB24 (0x34324258)
vulkan:   RG16 (0x36314752)
vulkan:   NV12 (0x3231564E)
vulkan:   AB4H (0x48344241)
vulkan:   XB4H (0x48344258)
vulkan:   AB30 (0x30334241)
vulkan:   XB30 (0x30334258)
vulkan:   AR30 (0x30335241)
vulkan:   XR30 (0x30335258)
vulkan: Creating Gamescope nested swapchain with format 58 and colorspace 0
wlserver: Running compositor on wayland display 'gamescope-0'
wlserver: [backend/headless/backend.c:17] Starting headless backend
wlserver: [xwayland/server.c:108] Starting Xwayland on :1
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Could not resolve keysym XF86CameraAccessEnable
> Warning:          Could not resolve keysym XF86CameraAccessDisable
> Warning:          Could not resolve keysym XF86CameraAccessToggle
> Warning:          Could not resolve keysym XF86NextElement
> Warning:          Could not resolve keysym XF86PreviousElement
> Warning:          Could not resolve keysym XF86AutopilotEngageToggle
> Warning:          Could not resolve keysym XF86MarkWaypoint
> Warning:          Could not resolve keysym XF86Sos
> Warning:          Could not resolve keysym XF86NavChart
> Warning:          Could not resolve keysym XF86FishingChart
> Warning:          Could not resolve keysym XF86SingleRangeRadar
> Warning:          Could not resolve keysym XF86DualRangeRadar
> Warning:          Could not resolve keysym XF86RadarOverlay
> Warning:          Could not resolve keysym XF86TraditionalSonar
> Warning:          Could not resolve keysym XF86ClearvuSonar
> Warning:          Could not resolve keysym XF86SidevuSonar
> Warning:          Could not resolve keysym XF86NavInfo
Errors from xkbcomp are not fatal to the X server
wlserver: [types/wlr_compositor.c:692] New wlr_surface 0x58f233d3a9a0 (res 0x58f233d148c0)
wlserver: [xwayland/server.c:273] Xserver is ready
pipewire: stream state changed: connecting
pipewire: stream state changed: paused
pipewire: stream available on node ID: 118
vblank: Using timerfd.
vulkan: Creating Gamescope nested swapchain with format 58 and colorspace 0
pipewire: renegotiating stream params (size: 1920x1080)
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
[2024-03-03 00:46:07.364] [MANGOHUD] [error] [overlay_params.cpp:1003] Failed to read presets file: '/home/alex/.config/MangoHud/presets.conf'
Selected GPU 0: NVIDIA GeForce RTX 4070 Laptop GPU, type: DiscreteGpu
[Gamescope WSI] Creating Gamescope surface: xid: 0x400000
[Gamescope WSI] Atom of T was wrong type. Expected XCB_ATOM_CARDINAL.
wlserver: [types/wlr_compositor.c:692] New wlr_surface 0x58f233ce6ed0 (res 0x58f233d1a640)
wlserver: [types/wlr_compositor.c:692] New wlr_surface 0x58f233ce6840 (res 0x58f233d1c590)
[Gamescope WSI] Made gamescope surface for xid: 0x400000
[Gamescope WSI] Surface state:
  steam app id:                  0
  window xid:                    0x400000
  wayland surface res id:        5
  layer client flags:            0x0
  server hdr output enabled:     false
  hdr formats exposed to client: false
xwm: got the same buffer committed twice, ignoring.
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
> Warning:          Could not resolve keysym XF86CameraAccessEnable
> Warning:          Could not resolve keysym XF86CameraAccessDisable
> Warning:          Could not resolve keysym XF86CameraAccessToggle
> Warning:          Could not resolve keysym XF86NextElement
> Warning:          Could not resolve keysym XF86PreviousElement
> Warning:          Could not resolve keysym XF86AutopilotEngageToggle
> Warning:          Could not resolve keysym XF86MarkWaypoint
> Warning:          Could not resolve keysym XF86Sos
> Warning:          Could not resolve keysym XF86NavChart
> Warning:          Could not resolve keysym XF86FishingChart
> Warning:          Could not resolve keysym XF86SingleRangeRadar
> Warning:          Could not resolve keysym XF86DualRangeRadar
> Warning:          Could not resolve keysym XF86RadarOverlay
> Warning:          Could not resolve keysym XF86TraditionalSonar
> Warning:          Could not resolve keysym XF86ClearvuSonar
> Warning:          Could not resolve keysym XF86SidevuSonar
> Warning:          Could not resolve keysym XF86NavInfo
Errors from xkbcomp are not fatal to the X server
[Gamescope WSI] Creating swapchain for xid: 0x400000 - minImageCount: 3 - format: VK_FORMAT_B8G8R8A8_UNORM - colorspace: VK_COLOR_SPACE_SRGB_NONLINEAR_KHR - flip: true
[Gamescope WSI] Created swapchain for xid: 0x400000 - imageCount: 3
[2024-03-03 00:46:07.480] [MANGOHUD] [error] [nvctrl.cpp:56] XNVCtrl didn't find the correct display
[Gamescope WSI] Swapchain recieved new refresh cycle: 4.17ms
(EE) failed to read Wayland events: Broken pipe
/usr/bin/prime-run: line 2: 121136 Killed                  __NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia "$@"
$ [Gamescope WSI] getLargestObscuringWindowSize: xcb_query_tree failed for window 0x400000.
[Gamescope WSI] getToplevelWindow: xcb_query_tree failed for window 0x400000.
[Gamescope WSI] canBypassXWayland: failed to get window info for window 0x400000.
[Gamescope WSI] getWindowRect: xcb_get_geometry failed for window 0x400000.
[Gamescope WSI] getWindowRect: xcb_get_geometry failed for window 0x400000.
[Gamescope WSI] getLargestObscuringWindowSize: xcb_query_tree failed for window 0x400000.
[Gamescope WSI] getToplevelWindow: xcb_query_tree failed for window 0x400000.
[Gamescope WSI] canBypassXWayland: failed to get window info for window 0x400000.
[Gamescope WSI] Creating swapchain for xid: 0x400000 - minImageCount: 3 - format: VK_FORMAT_B8G8R8A8_UNORM - colorspace: VK_COLOR_SPACE_SRGB_NONLINEAR_KHR - flip: false
```
</details>

![image](https://github.com/ValveSoftware/gamescope/assets/6632595/0d196abf-6584-4dea-810b-a98b8e563390)

**Comment by bno1** [comment]
I figured out I can run `gamescope prime-run vkcube` to run the game on nvidia and gamescope on the igpu to workaround the issue, but this only works on laptops.

**Comment by sharkautarch** [comment]
@bno1 see my posts on https://github.com/ValveSoftware/gamescope/issues/1166 for a workaround to allow you to run gamescope on nvidia

**Comment by bno1** [comment]
> @bno1 see my posts on #1166 for a workaround to allow you to run gamescope on nvidia

I tried both `nvidia-fix-latest-upstream-plus-extra-tweaks` and `nvidia-fix-latest-upstream` and neither fix the issues when running `prime-run gamescope vkcube` (still hangs, R and B still swapped).

Using `gamescope prime-run vkcube` or just `gamescope vkcube` it crashes:

```
$ gamescope vkcube
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
vulkan: selecting physical device 'Intel(R) Graphics (RPL-P)': queue family 0
vulkan: physical device supports DRM format modifiers
vulkan: vkAllocateDescriptorSets failed
terminate called without an active exception
Aborted (core dumped)
```

`gamescope prime-run vkcube` works fine on 3.14.2 except some bad frame pacing issue but it seems to go away when using `GAMESCOPE_DISABLE_TIMERFD=1`

**Comment by jarrard** [comment]
gamescope vkcube works fine for me but mangohud seems to break things

**Comment by prufaraSS** [comment]
if you're not on 535 driver version, this is the obvious reason why things are not working
also if you've tried to compile something or updated your system - delete steam with it dependencies and reinstall it - the package contains a lot of libs being actively used by games and (i suppose) directly affects gamescope performance.

**Comment by sharkautarch** [comment]
> if you're not on 535 driver version, this is the most obvious reason why things are not working
> also if you've tried to compile something or updated your system - delete steam with it dependencies and reinstall it - the package contains a lot of libs being actively used by games and (i suppose) directly affects gamescope performance.


I don’t think that steam libs actually affect performance much
Tho what could affect performance could be libs left behind by orphaned/uninstalled packages
On archlinux, you can install `lostfiles` to look for it: `lostfiles | grep '[/]usr[/](local[/]bin|bin)|[.]so.*'`

**Comment by bno1** [comment]
> Similar issue. Arch Linux, Nvidia driver 550.54.14, KDE 6, gamescope 3.14.2.

Fixed with the new 550.67 driver

**Comment by sharkautarch** [comment]
> > Similar issue. Arch Linux, Nvidia driver 550.54.14, KDE 6, gamescope 3.14.2.
> 
> Fixed with the new 550.67 driver


Question: are you currently using wayland or x11
Just asking in case the new 550.67 driver only works w/ gamescope on wayland or if it might only work on x11

**Comment by bno1** [comment]
> Question: are you currently using wayland or x11? Just asking in case the new 550.67 driver only works w/ gamescope on wayland or if it might only work on x11

Wayland

**Comment by Weather-OS** [comment]
Update: This issue still exists within the 550.67 drivers.
Note: drivers released prior to 545 don’t have this issue.

**Comment by sharkautarch** [comment]
> Update: This issue still exists within the 550.67 drivers. Note: drivers released prior to 545 don’t have this issue.


Huh...
Every new nvidia driver release version we hope that it'll be fixed
and every time, nvidia still disappoints
Classic Nvidia moment

**Comment by Weather-OS** [comment]
There’s a red herring as gamescope launches and works fine for like 3 - 5 minutes but the same thing still happens.

**Comment by profpyrus** [comment]
I am still having this issue as well, specifically trying to fix Fragpunk running in hyprland.
The game starts just fine, and when I try to join a match or go into the range, it works briefly before crashing. Any news on this?
