### ISSUE TITLE
Black screen when streaming with Steam Remote Play

### ISSUE THREAD

**Issue by lavadrop** [ValveSoftware/gamescope#1596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using any gamescope patches or a forked version of gamescope?

- [X] The issue occurs on upstream gamescope without any modifications

### Current Behavior

Streaming a game running under gamescope through the AppleTV Steam Link app results in a black video feed with normal sound and responsive to controller input.

### Steps To Reproduce

Configure launch options in host’s Steam to run through gamescope.
Launch any game from Steam Remote Play from the Steam Link app. 

### Hardware information

```markdown
- Distro: openSUSE Tumbleweed
- CPU: 8-core Ryzen 7 5800X3D
- GPU: [AMD/ATI] Navi 32 [Radeon RX 7700 XT / 7800 XT]
- Driver Version: Mesa 24.1.7
```

### Software information

```markdown
- Desktop environment: Plasma 6.2.2
- Session type: Wayland
- Gamescope version: 3.15.9-1.1
- Gamescope launch command(s): gamescope -W 2560 -H 1440 -r 144 —force-grab-cursor -—hdr-enabled —- %command%
```

### Which gamescope backends have the issue you are reporting?

- [X] Wayland (default for nested gamescope)
- [ ] DRM (default for embedded gamescope, i.e. gamescope-session)
- [ ] SDL
- [ ] OpenVR

### Logging, screenshots, or anything else

Capture in 1920x1080 at 59.76
Encoder: Desktop Black Frame + libx264 (4 threads)
Decoder: tvOS Metal hardware decoding
Stream latency: <1 ms input, 13.87 display
Ping: <1 ms (direct)
Incoming bitrate: 7226 kbit/s video: 75 kbit/s
Outgoing bitrate: 121 kbit/s
Packet loss: 0.00 %
Press F8 or BACK + X to save a snapshot in the remote computer

**Comment by mmleroux** [comment]
Exactly the same issue as described.

As soon as I stream a game launched within gamescope, I get a black screen. To not get the black screen, simply remove gamescope from the launch options and the game can stream anew.

Note that the sound works great and so does the controller input while having the black screen bug.

**Comment by ccampbell9** [comment]
I am experiencing the same problem as described as well. Trying to stream to a steam deck results in a black screen on the steam deck. Audio is present and the controller inputs are working, but there is no video display. Removing gamescope from a game's launch options fixes it.

**Comment by buckley310** [comment]
I am running into a black screen trying to stream gameplay as well.
Launching steam itself under gamescope and trying to stream it results in black screen on the client device, but controls seem to work, as others mentioned above.
In my case I first discovered this while trying to stream between two computers, but ended up mostly testing from my PC to my android phone.

Gamescope versions 3.14.17 through 3.16.1 (current latest) all have the issue.
Also tested current master branch (ef1e8dbe49da7ee87120c243f7d1d6935590cc76) and still has the issue.
Version 3.14.16 works for me.

After some bisecting:
revision b02d87f3efa950a3e093ec962cfb002bbbc7f7f3 is broken.
revision 64a34763cdd2b49b8c3ccd3751afd4ece1223564 is working.


In case it's relevant:
```
- Distro: NixOS unstable
- CPU: Intel i9-12900H
- GPU: Nvidia RTX 3080 mobile
- Driver Version: Nvidia 550.142

- Desktop environment: GNOME 47
- Session type: X11
- Gamescope version: see above
- Gamescope launch command(s): gamescope -e steam
```

**Comment by mprasil** [comment]
@buckley310 how did you override the gamescope version? I had to drop one nix patch:

```nix
  gamescope = pkgs.gamescope.overrideAttrs (finalAttrs: previousAttrs: {
    version = "3.14.16";

    src = pkgs.fetchFromGitHub {
      owner = "ValveSoftware";
      repo = "gamescope";
      tag = finalAttrs.version;
      fetchSubmodules = true;
      hash = "sha256-tijFVOIMW+nkot/uRP0PNZBYZkZMMt1PcAN5+3SWzW4=";
    };

    # Drop patch that does not work with 3.14.X
    patches = lib.filter (patch: ! lib.hasSuffix "reaper.patch" patch) previousAttrs.patches;
    postPatch =
      ''
        mkdir -p src/Utils
        touch src/Utils/Process.cpp
      ''
      + previousAttrs.postPatch;
  });
```

But even this version does not work for me. In some games I get screen stuck on some initial frame, in most black screen. What's interesting is the Steam overlay seems to be working fine I just can't see game itself.

Makes me wonder if @misyltoad commit you linked is relevant in my case - I can't see any difference in behavior, but the issues are pretty much the same as in issue description.

**Comment by buckley310** [comment]
While testing, I actually just checked out older versions of the nixpkgs repo until I got to the point where the package started working again, and then started editing the nix file in the repo itself for more fine-grained version testing.

How I'm actually using gamescope on my machine today is simply `nix run -- 'nixpkgs/nixos-24.05#gamescope' -e steam`

**Comment by mprasil** [comment]
@buckley310 are you using unstable NixOS for your system? The 24.05 gamescope on top of 24.11 NixOS does not seem to work for me. I wonder if it might be some combination of dependencies and gamescope version that is problematic.

**Comment by buckley310** [comment]
@mprasil yep, 24.05 gamescope on unstable nixos.

**Comment by Uklosk** [comment]
> I am running into a black screen trying to stream gameplay as well. Launching steam itself under gamescope and trying to stream it results in black screen on the client device, but controls seem to work, as others mentioned above. In my case I first discovered this while trying to stream between two computers, but ended up mostly testing from my PC to my android phone.
> 
> Gamescope versions 3.14.17 through 3.16.1 (current latest) all have the issue (checked many, but not every single version). Also tested current master branch ([ef1e8db](https://github.com/ValveSoftware/gamescope/commit/ef1e8dbe49da7ee87120c243f7d1d6935590cc76)) and still has the issue. Version 3.14.16 works for me.
> 
> After some bisecting: revision [b02d87f](https://github.com/ValveSoftware/gamescope/commit/b02d87f3efa950a3e093ec962cfb002bbbc7f7f3) is broken. revision [64a3476](https://github.com/ValveSoftware/gamescope/commit/64a34763cdd2b49b8c3ccd3751afd4ece1223564) is working.
> 
> In case it's relevant:
> 
> ```
> - Distro: NixOS unstable
> - CPU: Intel i9-12900H
> - GPU: Nvidia RTX 3080 mobile
> - Driver Version: Nvidia 550.142
> 
> - Desktop environment: GNOME 47
> - Session type: X11
> - Gamescope version: see above
> - Gamescope launch command(s): gamescope -e steam
> ```

I can confirm commit b02d87f3efa950a3e093ec962cfb002bbbc7f7f3 breaks remote play inside a nested gamescope session on NVIDIA.

**Comment by Uklosk** [comment]
A collateral issue by this is that Steam does not hook properly (i.e. no Steam overlay, no remote play) to some non-steam games/apps (e.g. Yuzu emu), so the only way to use them with Remote Play is inside a wayland session, which is broken right now, so no absolute way to remote play them on Linux using Steam.

**Comment by systox** [comment]
Issue persists

**Comment by adueppen** [comment]
I'm experiencing a similar issue to this where sometimes I get a black screen but other times I get a fast slideshow of single frames, some of which are minutes or even hours old. This happens with other things too so I suspect the issue is ultimately in Remote Play (or Pipewire/Mutter) but it happens every time I use gamescope (on Fedora 42 with GNOME Wayland)

https://github.com/user-attachments/assets/52316826-fb8b-4e53-b16b-8e473c286225

Note the time at the top, I had been experimenting with different gamescope options in the hope one would fix it hence the WSI layer error.

**Comment by internatt** [comment]
> > Replying to [#1596 (comment)](https://github.com/ValveSoftware/gamescope/issues/1596#issuecomment-2613806866)
> 
> I can confirm commit [b02d87f](https://github.com/ValveSoftware/gamescope/commit/b02d87f3efa950a3e093ec962cfb002bbbc7f7f3) breaks remote play inside a nested gamescope session on NVIDIA.

Also here to confirm this. I'm running Bazzite in -deck mode. From within -deck / -tenfoot which is using gamescope as the session microcompositor, I experience the black screen. Audio **_does_** appear to work, but no input pass-through. Streaming from the same machine on KDE-Plasma desktop, streaming works as expected.

**Comment by GGORG0** [comment]
Hey, I'm experiencing the same issue, on Arch and NVIDIA. Is there any known fix to this? I tried compiling from the commit right before the one mentioned above (by using the PKGBUILD for the `gamescope-git` AUR package and changing the Git URL to the commit) and it still didn't work (black screen). It also doesn't work when running gamescope in a TTY.

Exactly the same symptoms - black screen, audio and gamepad work (the on-screen gamepad layout on a phone also dynamically changes according to the running game).

**Comment by lukewilde** [comment]
I ran into this issue trying to stream a game from my PC to my Steamdeck.

Is there another way I can run a game on Linux at whatever resolution / aspect ratio I want? FYI, I'm trying to stream Clair Obscur from desktop with 5120x1440 to either the Steamdecks 1280x800 or my TVs 4096x2160 (or 2560x1440). The games resolution settings don't play well on my setup without gamescope.

On Windows I used to use https://github.com/ClassicOldSong/Apollo which solved this problem for me.

**Comment by bernhardberger** [comment]
I'm having the same issue inside a gamescope-session when trying to use Steam Link. Black screen, Audio and Controls work. Using CachyOS with boot dorectly into a gamescope session on nvidia.

Streaming with Sunshine and Moonlight works fine.

**Comment by nauzethc** [comment]
I'm having the same problem. I can use Remote Play running Steam directly from Plasma Desktop, but I'm getting black screen if I run Steam within Gamescope compositor (using gamescope-session or running from Plasma Desktop with Wayland). Controls and audio work. 

To confirm if it was a problem with Proton, I also used a native Linux game. I ran Hollow Knight Silksong, and the weird thing is that I can see the mouse cursor within the game (I assume it's a sprite that the game itself renders on another layer), but the background remains black.

```
- Distro: Archlinux
- Desktop environment: Plasma 6.5.5
- Session type: Wayland
- GPU: NVIDIA 4070 Super
- Gamescope version: 3.16.20-1
- Gamescope launch command(s): gamescope -W 2560 -H 1440 -r 120 --fullscreen --hdr-enabled --hdr-itm-enable --adaptive-sync --steam --mangoapp -- /usr/bin/steam -steamdeck -steamos3 -gamepadui
```

**Comment by Ramalama2** [comment]
LOL, this issue is 2 Years old, WTF Valve....

However, the fix is pretty simple:
just add to src/rendervulkan.cpp, into the vulkan_acquire_screenshot_texture() function:
3616 +      screenshotImageFlags.bSampled = true;

Here is the Code Block where it belongs to:
```
3613        screenshotImageFlags.bMappable = true;
3614        screenshotImageFlags.bTransferDst = true;
3615        screenshotImageFlags.bStorage = true;
3616 +      screenshotImageFlags.bSampled = true;
3617        if (exportable || drmFormat == DRM_FORMAT_NV12) {
3618          screenshotImageFlags.bExportable = true;
3619          screenshotImageFlags.bLinear = true; // TODO: support multi-planar DMA-BUF export via PipeWire
```

The reason is pretty simple, the screenshot texture created by vulkan_acquire_screenshot_texture() is missing the VK_IMAGE_USAGE_SAMPLED_BIT flag.
The NV12 shader attempts to sample it as a sampler2D (combined image sampler), which is a Vulkan spec violation — the NVIDIA driver returns black pixels.

**Comment by nauzethc** [comment]
> Replying to https://github.com/ValveSoftware/gamescope/issues/1596#issuecomment-3890263994

I've tried it and **it works**! 

But now two other problems have appeared (at least that I'm aware of).

The colors aren't displaying correctly. I think the issue is with the RGB bits order because they're displayed rotated (what should be blue is actually red, and what should be red is actually blue). I've tried both HDR enabled and disabled, and the problem persists. I'm providing a screenshot of FF7 Remake so you can see it.

<img width="1906" height="1065" alt="Image" src="https://github.com/user-attachments/assets/e8940b11-6cc7-47d6-a8fa-7bcd7ed5a43f" />

The other problem is that for some reason the inputs are being duplicated, both from the host (using a controller) and from the client (using the Steam Deck buttons). Every time I press a button on either end, two inputs are generated (if you move the D-pad in a menu, it moves twice).

**Comment by Ramalama2** [comment]
Im Sorry, but im not using gamescope and not want to,
the reason i provided this fix at all is, that on my way building a headless game streaming/desktop server i stumbled across gamescope because it supports Frame-Pacing, so i tryed it for like 30min stumbled against this bug, searched a solution on github, camed across this thread and fixed in the end for myself to find out how bad gamescope really is.

Gamescope has a ton of issues and it looks for me like Valve mostly hacked something together, that works somehow. They removed a ton of nice features that they could use from the submodules.

Basically in short, im not here to fix anything. I continued my way and i camed across KWin, it's a Wayland Compositor with 3x Buffering and absolutely perfect Frame-Pacing implementation, it plays in a completely different league.

But i cant recommend it for everyone, i think that people want to use Steam Remote-Play (which is pure x32 Crap, that somehow works either)
However due to ease of use and Frame-Pacing+FSR, Steam Remote-Play is actually perfect for most people, because it will feel smoother and better as Sunshine+Moonlight.

(For myself with a Blackwell RTX6000 which doesnt support x32 Cuda, Steam Remote-Play is not a solution for my project, its simply incompatible -> no HEVC)
I need HEVC + Frame Pacing + VBR + Jitter tuning and much more for the best Streaming Experience over WAN.
So im building myself a Custom Stack, that will provide a nice experience.

IF gamescope would have at least a good codebase and Steam would finally port their App to x64, i surely would provide a lot of PR fixes, that i need myself at least.
But in this stage, as im definitively not going to use it, im sorry, i dont want to waste my time.

PS: About your bug, yes you are correct, the colors arent 100% correct, this is because gamescope has a ton more issues, they send to the encoder a wrong rgb format which is actually unsupported but works somehow.
I think this might be okay for AMD, as the whole code is somehow mainly made to work somehow with amd cards (still ignoring all specs) but gamescope is definitively not made for Nvidia or even tested on nvidia cards. (The nvidia drivers are more restrictive too)

However whatever i say wont help you. Maybe you could check the Wolf (Games on Whales) Project.
Its a Docker based streaming solution (i didnt tryed it, but im stealing code for myself from their project, like fake-udev. Their codequality is absolutely great).
And its the only easy probably "good working" smooth experience for WAN/Lan Streaming solution i camed across.

But not for myself again, because im making my own solution in LXC Container not Docker, maximally tuned for WAN Streaming and compiling everything with Cuda 13.1/Zen4 Optimizations etc...
Basically useless for everyone else other than exactly my server and for myself.

Sorry and Cheers :-)

**Comment by Ramalama2** [comment]
PS, if someone is interested, I found my solution that gives the best streaming experience. I filed a PR:
https://github.com/LizardByte/Sunshine/pull/4724

I'm not sure if the PR is going to be merged, but it is a better solution overall than gamescope — no issues with colors, working HDR with any card, works in containers, and KWin's frame pacing delivers equally full complete pictures at a constant fps to Moonlight.
--> No vsync needed!

It's harder to set up, indeed, and KDE Plasma desktop is a bloat of packages...
But as a benefit you get a desktop too, if that's worth it.
So it's not for everyone, but it delivers a better experience overall.

**Comment by lavadrop** [comment]
> PS, if someone is interested, I found my solution that gives the best streaming experience. I filed a PR:
> https://github.com/LizardByte/Sunshine/pull/4724
> 
> I'm not sure if the PR is going to be merged, but it is a better solution overall than gamescope — no issues with colors, working HDR with any card, works in containers, and KWin's frame pacing delivers equally full complete pictures at a constant fps to Moonlight.
> --> No vsync needed!
> 
> It's harder to set up, indeed, and KDE Plasma desktop is a bloat of packages...
> But as a benefit you get a desktop too, if that's worth it.
> So it's not for everyone, but it delivers a better experience overall.

Sunshine is completely broken in Wayland, officially, since KMS grab is blocked by default now. The preview version is also broken when installed via flatpak since it lacks several permissions.

**Comment by cmspam** [comment]
Here is a complete fix, fixing both the black screen and the colors on nvidia.
EDIT: I submitted it upstream as a PR.
https://github.com/ValveSoftware/gamescope/pull/2094

**Comment by Naharie** [comment]
The patch suggested by @Ramalama2 is still more or less accurate. It is in a different file now, but the change is the same. Just patched and tested on NixOS and while it doesn't fix other input problems, it does fix the black screen when streaming as long as I run steam with `-pipewire` because I'm on wayland.

I've attached an updated patch file for the convenience of anyone who comes by later.

[gamescope.patch](https://github.com/user-attachments/files/27853108/gamescope.patch)

**Comment by neverjacko** [comment]
> Just patched and tested on NixOS and while it doesn't fix other input problems, it does fix the black screen when streaming as long as I run steam with `-pipewire` because I'm on wayland.

Could you maybe share the nix config you added to patch it @Naharie ? Would love to try it out myself.

**Comment by Naharie** [comment]
@neverjacko Absolutely. Assuming you have the patch downloaded as `gamescope.patch` in the same folder as the file you configure steam in then this is the relevant bit:
```nix
{ pkgs
, ...
}:

{
  programs.steam = {
    enable = true;
    extraPackages = with pkgs; [
      (gamescope.overrideAttrs (finallAttrs: previousAttrs: {
        patches = previousAttrs.patches ++ [ ./gamescope.patch ];
      }))
    ];
  };
}
```

That patch doesn't include the nvidia parts as I don't currently have access to a machine with an nvidia gpu to test on. If you do have an nvidia card and have the swapped red and blue channels (assuming my existing patch fixes the black screen), just tag me again and I can try to throw together a combined patch file for that with the changes from [#2094](https://github.com/ValveSoftware/gamescope/pull/2094) (no promises about it working, though, given that I wouldn't be able to test it myself).
