### ISSUE TITLE
Wrong color space on an external display when playing SDR games with the HDR toggle set to ON

### ISSUE THREAD

**Issue by sew700** [ValveSoftware/gamescope#1887]
#### Your system information

- Steam client version: 1748914100
- SteamOS version: 3.7.8 Stable 20250522.2
- Opted into Steam client beta?: No
- Opted into SteamOS beta?: No
- Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
Context: Steam Deck OLED connected to an external display, capable of HDR, via HDMI dock is being used as a Moonlight streaming client (Moonlight assumingly is not a culprit here, I will come back to this later). 
Capturing screenshots for an illustration is quite difficult, or rather impossible, since “Color Vibrance” does not affect screenshots and Steam Deck is not capable of capturing HDR screenshots, but I found an [issue](https://github.com/ValveSoftware/SteamOS/issues/1703) with suitable photos illustrating the aforementioned problem just fine in my case. 

1. Moonlight is streaming SDR content, and the Steam Deck's HDR toggle is set to OFF. Everything looks totally fine. ✅
2. Moonlight is streaming HDR content, and the Steam Deck's HDR toggle is set to ON. Everything looks totally fine. ✅
3. Moonlight is streaming SDR content, and the Steam Deck's HDR toggle is set to ON. Here is where it goes wrong. ❌

Everything below is based only on my personal experience, research, and observations, since I am not a verified color expert. 

SDR games render in the BT.709 color space, whereas HDR games use BT.2020. Thus, the external monitor nonetheless treats incoming “forced” HDR as BT.2020, while in fact it should be BT.709. Since BT.2020 is wider than the BT.709 color space, one can observe so-called “oversaturated” colors. Thankfully, my LG TV is capable of HDMI signalling override, which lets me do some tinkering. If I set colorimetry to BT.709 (or should it be BT.601? The difference between them is quite subtle), the colors roll back to normal. Once I set colorimetry to BT.2020 (or P3 D65 — the difference between the two is invisible to the naked eye), colors are again oversaturated.  
An unfortunate side effect of this trick is that native HDR games, on the other hand, become washed out (or, some may say, undersaturated), so it is more of a workaround than a silver bullet.

**Important** — SteamOS UI is also affected, e.g., Xbox controller button A (Select) by default has a slight yellow tint, the same goes for button B (Back). With the HDR toggle set to ON the button A gets a toxic green look, while the button B becomes pure red. Setting colorimetry to BT.709 rolls back both buttons (and overall SteamOS appearance) to normal. That's why I think this is a system-level issue and has nothing to do with Moonlight. 

You reasonably may wonder, “Why would you bother? Just play in SDR, and that is it.” Well, yes and no. Some TVs and monitors are capable of their peak brightness only in the HDR mode, and SDR looks just too dim. Once you get those extra nits, you do not want to miss them anymore.

Some side observations that may be helpful:

- While looking for the perfect Moonlight client, I stumbled upon Apple TV 4K. It had the opposite problem — SDR games with HDR active were washed out. I tried tinkering with the source code. [Here](https://github.com/moonlight-stream/moonlight-ios/blob/da470355257ddc843d6f3354bd621d0577630fe6/Limelight/Stream/Connection.m#L424) I added `_streamConfig.colorSpace = COLORSPACE_REC_709;` and made a custom build. With only a single line of code, SDR games became fine, while HDR games were not affected at all, i.e., both SDR and HDR games looked fine simultaneously without any fuss.
- PS5 is also capable of “always HDR” mode, and it manages pretty well. SDR-only games on the Steam Deck with colorimetry set to BT.709 on my LG TV look exactly like they do on PS5.

In case I discover something new, I will surely share it in this thread.

**Comment by SerjTargarien** [comment]
Any updates or developments on this? I can confirm I'm having the exact same situation on my LG C1 TV Having to manually toggle a different (and hidden) color space setting on my TV is such a turn off from using gamescope session in any distro.

Is anyone actively working on fixing the problem, or will it be a very long waiting game till it's eventually fixed?

**Comment by cchulo** [comment]
same issue on a sony X90L with both steam deck oled running latest stable steamos. Sort of related, I run into this as well with bazzite on my htpc when booted into gamescope-session

**Comment by cchulo** [comment]
because this also happens on bazzite, not just steamos, do you think its an issue with gamescope instead? would it make more sense to make this issue here instead? https://github.com/ValveSoftware/gamescope

**Comment by SerjTargarien** [comment]
I can confirm it also happens in CachyOS, so, yes, it's a gamescope-session / gamescope issue

**Comment by sew700** [comment]
@cchulo, @SerjTargarien, interesting! Can you confirm that this bug also affects your OS UI, not just games?

**Comment by SerjTargarien** [comment]
I can confirm it also affects the UI.

**Comment by sew700** [comment]
Then it is about time I created a new issue in the gamescope repo. I am only afraid that I am sort of a fledgling when it comes to Linux, Wayland, and all that stuff.

**Comment by cchulo** [comment]
> Then it is about time I created a new issue in the gamescope repo. I am only afraid that I am sort of a fledgling when it comes to Linux, Wayland, and all that stuff.

all good :) i actually thought the colors looked off for almost an entire year and then i booted into windows with calibrated HDR. I went back to bazzite and i thought something was wrong, then i found your issue. Appreciate you articulating this issue, i didn't even know how to put this issue into words, I am not a color expert, was afraid of posting an issue that simply read "the reds are too red"

**Comment by sew700** [comment]
Wow, great! Thank you, @kisak-valve

**Comment by cchulo** [comment]
after a bit of tinkering, switching back and forth from windows, i think i solved my problem on sony X90L, i have to set hdmi video signal to use full rgb, and even with HDR enabled, SDR seems to now be in the correct color space, for me anyway. I am using a cablematters dongle to convert DP to HDMI 2.1 to get 4k@120

**Comment by SerjTargarien** [comment]
Tried to fix it with an equivalent setting in my LG C1 (it appears in this TV you have to go to the HDMI inputs screen and set the specific input to "PC"). It's not fixed. Seems like something that should be fixed sending the correct information via the HDMI cable from the computer instead of tinkering with the TV, as other devices (consoles and windows PCs) can take care of it automatically.

**Comment by sew700** [comment]
@cchulo 
> i have to set hdmi video signal to use full rgb,

Just to clarify (since different TV brands call the same settings differently), do you mean black level (limited 16-235 and full RGB 0-255) or chroma subsampling (4:2:2, 4:4:4)? 

And, well, neither of those settings can affect color space. Black level mismatch may result in the wrong contrast level, and chroma subsampling impacts picture clarity.

Nonetheless, I will tinker with those settings as well.

**Comment by cchulo** [comment]
@SerjTargarien in my case, I am using a dongle, which i worry is messing with the signal the TV is receiving. Are you using any dongles on your end.

@sew700 I think it is full rgb here is what the setting reads ![image](https://github.com/user-attachments/assets/78bef8ab-a904-4b49-aea8-0861228683eb) under the video signal section in my sony tv

**Comment by sew700** [comment]
> I think it is full rgb here is what the setting reads

[A video from HDTVTest](https://youtu.be/S0G8sHcFQq8?si=E-R7yaUb5W4i5K55&t=857) regarding this setting.
_(On LG TVs it used to be "black level", but nowadays it is also "video range")_ 

It cannot affect color space. AFAIK, Steam Deck outputs a full RGB range, and due to DP->HDMI conversion, your TV may choose the wrong video range if set to auto. Thus, you may have to set it to full manually.

**Comment by SerjTargarien** [comment]
No dongle on my end. Just a short HDMI 2.1 cable.

**Comment by sew700** [comment]
> No dongle on my end. Just a short HDMI 2.1 cable.

Ouch, I always forget that there are other distros with gamescope. But nonetheless, video range and color space are different things.

**Comment by sew700** [comment]
The problem is still present on the fresh Steam Deck OLED update.
- Steam client version: 1751405894
- SteamOS version: 3.7.13 Stable 20250630.1

**Comment by prestonsmartuk** [comment]
> The problem is still present on the fresh Steam Deck OLED update.
> 
> * Steam client version: 1751405894
> * SteamOS version: 3.7.13 Stable 20250630.1

Same. Pesent my end too. Connected to TCL C805 TV. When docked, HDR is oversatured and blacks are crushed, only applicable to OLED Steam Deck.

**Comment by cchulo** [comment]
> > I think it is full rgb here is what the setting reads
> 
> [A video from HDTVTest](https://youtu.be/S0G8sHcFQq8?si=E-R7yaUb5W4i5K55&t=857) regarding this setting.
> _(On LG TVs it used to be "black level", but nowadays it is also "video range")_ 
> 
> It cannot affect color space. AFAIK, Steam Deck outputs a full RGB range, and due to DP->HDMI conversion, your TV may choose the wrong video range if set to auto. Thus, you may have to set it to full manually.

what i meant is setting TV to full fixed crushing blacks. Colors are still oversaturated for me unless i also modify the color profile to the appropriate one for SDR content

i think i can live with oversaturated colors, its crushing blacks that was preventing me from playing dark games

**Comment by joeblack2k** [comment]
ah stumbled on this thread 

my 6950XT powered SteamOS machine is running fine on my C1 Oled but when i hook it up to my TK700sti projector it has a green tint. like explained here. i was searching for a solution (forcing edid to 10bit.. perhaps) i hope this will be fixed soon for now i just swap HDR off when i play a SDR game

**Comment by mennoliefstingh** [comment]
This was fixed on my LG G2 by going into the LG's (full) settings, choosing General -> External Devices -> HDMI settings. There, make sure 4:4:4 Pass Through is enabled and HDMI Deep Colour is disabled.

**Comment by sew700** [comment]
> HDMI Deep Colour is disabled.

This is highly discouraged. HDMI deep color is mandatory for hdmi 2.1 features and HDR stuff

**Comment by NyaomiDEV** [comment]
I will add myself here - having a bespoke Arch configuration, running Gamescope nested inside Plasma because I only seldom use it. Games and the Big Picture UI look wrong, overly saturated indeed, because it seems that Steam itself forces Gamescope to be HDR at all times. Testing Gamescope ALONE with `--hdr-enabled` on SDR content effectively looks good, but I would not know if it wants to report itself as SDR to KWin, or if it color-maps correctly within itself.

9070XT btw

**Comment by ClementNerma** [comment]
This is still a problem to this day, and a pretty infuriating one.
With HDR on I didn't find any way to make colors correct - setting the RGB range in SteamOS' display settings, setting the 'black level' setting on my tv (which is actually the RGB range), nothing works...

**Comment by joeblack2k** [comment]
I made a small, reversible test script for the green/magenta HDR tint issue:

https://github.com/nijssencomputers/gamescope-green-tint-fix

What it does:
- Reads the EDID of your currently connected display.
- Keeps the display’s own red/green/blue primaries.
- Replaces only its advertised white point with D65.
- Creates a Gamescope profile matched only to that exact display vendor/product ID.
- Does NOT force BT.709, BT.2020, or HDR.

This is useful if the HDR image has a strong green or magenta tint that may be caused by a bad EDID white point.

In Desktop Mode, open a terminal and run:

curl -LO https://raw.githubusercontent.com/nijssencomputers/gamescope-green-tint-fix/main/superscript-gamescope-green-tint.sh
chmod +x superscript-gamescope-green-tint.sh
./superscript-gamescope-green-tint.sh --apply

Important:
1. Disconnect extra displays first. The script intentionally stops if more than one display is connected.
2. Restart Game Mode or reboot after applying it.
3. Test the same HDR scene that showed the tint.

If the image is worse or unchanged, remove the test profile:

./superscript-gamescope-green-tint.sh --remove

Then restart Game Mode or reboot again.

This is an unofficial and reversible test, not a universal HDR/colour-space fix. Do not use it to fix ordinary SDR oversaturation caused by “always HDR”; this specifically targets a bad display white point.

**Comment by em0g** [comment]
I think I may have found another piece of this issue, specifically affecting native HDR content.

I’m running SteamOS on a desktop PC connected directly via HDMI to an LG OLED. Native HDR works in the sense that black levels, peak highlights and general HDR luminance look correct, but colors are noticeably undersaturated/washed out.

I’ve reproduced the same behavior in multiple native HDR games:

• Resident Evil 7
• Resident Evil Village
• Cyberpunk 2077

SDR looks considerably more saturated, while HDR has correct blacks/highlights but noticeably reduced color saturation.

System

• SteamOS 3.8.16
• Gamescope 3.16.23.4
• AMD Radeon RX 9700 XT
• LG OLED G3 connected via HDMI
• HDR enabled globally in SteamOS

I initially suspected Proton/Lutris, but the running game process has the expected HDR/Gamescope environment, including:

```text
DXVK_HDR=1
ENABLE_GAMESCOPE_WSI=1
STEAM_GAMESCOPE_HDR_SUPPORTED=1
STEAM_GAMESCOPE_COLOR_MANAGED=1
GAMESCOPE_WAYLAND_DISPLAY=gamescope-0
```

Testing PROTON_ENABLE_HDR=1 and the Wine Wayland path did not change the result.

Interesting finding: Gamescope Color Management

While a native HDR game is running and visibly undersaturated, Gamescope reports:

```text
GAMESCOPE_DISPLAY_HDR_ENABLED(CARDINAL) = 1
GAMESCOPE_HDR_OUTPUT_FEEDBACK(CARDINAL) = 1
GAMESCOPE_DISPLAY_SUPPORTS_HDR(CARDINAL) = 1
GAMESCOPE_COLOR_MANAGEMENT_DISABLE(CARDINAL) = 0
```

If I disable Gamescope Color Management while the game is running:

```bash
xprop -root -display :0 \
  -f GAMESCOPE_COLOR_MANAGEMENT_DISABLE 32c \
  -set GAMESCOPE_COLOR_MANAGEMENT_DISABLE 1
```

the colors immediately change and native HDR looks correct.

No game restart, Gamescope restart, display mode change or HDR toggle is required. The difference happens live.

Setting the property back to 0 immediately brings the undersaturated HDR colors back.

I can therefore reproduce the issue essentially as an on/off switch:

```text
Gamescope Color Management ON
    -> native HDR undersaturated

Gamescope Color Management OFF
    -> native HDR colors correct
```

The downside is that disabling Color Management also makes the Steam UI look wrong, so it isn’t a proper solution. As a temporary workaround I currently use a wrapper around HDR games which disables Color Management when the game starts and restores it when the game exits.

EDID / colorimetry

I also checked the EDID. Gamescope’s patched EDID is byte-for-byte identical to the display EDID (cmp returns 0).

The base EDID reports:

```text
Red:   0.6396, 0.3300
Green: 0.2998, 0.5996
Blue:  0.1503, 0.0595
White: 0.3125, 0.3291
```

The CTA extension also correctly advertises:

```text
Colorimetry Data Block:
  BT2020YCC
  BT2020RGB

HDR Static Metadata Data Block:
  SMPTE ST2084
  Hybrid Log-Gamma
```

Interestingly, the Gamescope log says:

```text
[colorimetry]: EDID with colorimetry detected. Using it
```

and then reports the base EDID primaries above.

The EDID also contains the LG Dolby Vision block with wider display primaries and a target maximum PQ luminance corresponding to approximately 1037 cd/m².

I don’t know whether the EDID primary handling is actually related, so I don’t want to draw conclusions from that alone. However, the reproducible relationship with GAMESCOPE_COLOR_MANAGEMENT_DISABLE seems significant.

This also appears very similar to ValveSoftware/SteamOS#1314, where native HDR games, including Cyberpunk 2077 on an LG OLED, were reported as having washed-out/undersaturated colors.

Hopefully the ability to toggle the problem live using GAMESCOPE_COLOR_MANAGEMENT_DISABLE helps narrow down where in the Gamescope HDR/color-management pipeline this is happening.

**Comment by lesiw** [comment]
I purchased a Steam Machine and this bug is still present. It's a bit embarrassing to launch a product whose entire purpose is to be plugged into an external display and it ships with this bug, sending customers like me to GitHub in search of answers!

The only viable workaround I've found for now is to boot into Desktop Mode + Big Picture with HDR switched on in KDE. For what it's worth, KWin does this properly. The fault here lies entirely with gamescope.
