### ISSUE TITLE
FSR/Sharp hanging/crashing Steam Deck when reshade is active

### ISSUE THREAD

**Issue by Moonveil-Kanata** [ValveSoftware/gamescope#1903]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Are you using any gamescope patches or a forked version of gamescope?

- [x] The issue occurs on upstream gamescope without any modifications

### Current Behavior

Hi,
I love how reshade gaining a huge performance on steamos 3.7.8.
Which make me able to use reshade, to fix screen problem like mura without big performance hit.
Or even playing retro games like doom with crt reshade shader.

Unfortunately, when scaling filter is set to sharp. The sd starts hanging, crashing, and even rebooting.
It can be reproduced so easy by enabling "HDR Debug Visualization" on developer setting to trigger the reshade.

My tests is using Elden Ring, because I always use lower resolution in this game. But the problem should be occurs on every game.

### Steps To Reproduce

1. Launch any game, for example Elden Ring on low resolution and HDR
2. Navigate into Settings/Developer, enable "Waveform / Color Gamut" on "HDR Debug Visualization" dropdown
3. Game starts hang and colors changing

### Hardware information

```markdown
Steam Deck OLED 512GB
```

### Software information

```markdown
SteamOS 3.7.8 Game Mode
```

### Which gamescope backends have the issue you are reporting?

- [ ] Wayland (default for nested gamescope)
- [x] DRM (default for embedded gamescope, i.e. gamescope-session)
- [ ] SDL
- [ ] OpenVR

### Logging, screenshots, or anything else

![Image](https://github.com/user-attachments/assets/547d805b-938e-4d23-af79-709b1ac87917)

**Comment by matte-schwartz** [comment]
Could you switch to the Beta or Preview channel and see if it still happens there? There were some fixes related to FSR upscaling.

**Comment by Moonveil-Kanata** [comment]
Yes, I was tried to update into beta 3.7.12 and revert back to stable because the problem still occurs. Not tried on the preview channel though, if I checked correctly the preview channel change log is same as the beta.

**Comment by matte-schwartz** [comment]
Ok thanks, I can reproduce the performance issue. Will try to look into it. The pink screenshot you posted is what was fixed on Beta but seems unrelated.

**Comment by Moonveil-Kanata** [comment]
Really appreciate it Matthew! Looking forward for the update, thanks.

**Comment by matte-schwartz** [comment]
Looks like a preemptive upscaling issue specifically with the Waveform / Color Gamut reshade overlay option. Doesn't seem like a recent issue either. For some reason the reshade overlay also gets doubled when it's using it. The other HDR debug techniques seem fine in terms of performance though.

Preemptive upscaling:

![Image](https://github.com/user-attachments/assets/af2c6767-6d33-4aac-b9ee-9dafb2256dfe)


Non-preemptive upscaling:

![Image](https://github.com/user-attachments/assets/a877ab04-0617-41a2-8ebf-134e28b542f7)

**Comment by Moonveil-Kanata** [comment]
Ah.. I see. Yeah the other HDR visualization is working perfect. I'm back to steamos beta to test this. Right, the pink glitch is fixed on the beta. Unfortunately, for custom reshade it seems still have the problem. Even on desktop mode.

**Steps To Reproduce:**
I use these reshade for test purposes [FakeHDR](https://github.com/byxor/thug-pro-reshade/blob/master/THUG%20Pro/reshade-shaders/Shaders/FakeHDR.fx), [FilmGrain](https://github.com/Otakumouse/stormshade/blob/master/v3.X/reshade-shaders/Shader%20Library/Recommended/FilmGrain.fx)

On desktop mode, I tried again Elden Ring lowering the resolution. With this command with FSR active
`gamescope -F fsr --reshade-effect FakeHDR.fx -- %command%`
- While the FakeHDR, sometimes crash the game. But sometimes, it runs but the screen goes flickering.
- While the FilmGrain.fx always crash the game.

While on game mode, I use something like this. And, causing my deck to crash+reboot
`bash -c "DISPLAY=:0 xprop -root -f GAMESCOPE_RESHADE_EFFECT 8s -set GAMESCOPE_RESHADE_EFFECT 'FilmGrain.fx'; %command%; DISPLAY=:0 xprop -root -remove GAMESCOPE_RESHADE_EFFECT"`

All of this, without fsr it's working flawlessly.
